AllCops:
  TargetRubyVersion: 2.3

##################### Style ####################################

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

##################### Metrics ##################################

Metrics/LineLength:
  Max: 140

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

##################### Lint ##################################

##################### Rails ##################################

Rails:
  Enabled: true
