default: &default
  adapter:   postgresql
  encoding:  unicode
  pool:      <%= Rails.application.secrets.db_pool %>
  host:      <%= Rails.application.secrets.db_host %>
  database:  <%= Rails.application.secrets.db_name %>
  username:  <%= Rails.application.secrets.db_user %>
  password:  <%= Rails.application.secrets.db_pass %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
