# Be sure to restart your server when you modify this file.

development:
  secret_key_base: 26cef78df5a6dbacc5702a1fd3a1f738eb90ee2a13f6e7c0b54e13c08bde693bf2cd45821fa14ba2c620303226c8dbdbd6a01c3a4c807ff41e02f31403fca6e7
  db_host: <%= ENV['DESTINY_DEVELOPMENT_HOSTNAME'] %>
  db_name: <%= ENV['DESTINY_DEVELOPMENT_DATABASE'] %>
  db_user: <%= ENV['DESTINY_DEVELOPMENT_USERNAME'] %>
  db_pass: <%= ENV['DESTINY_DEVELOPMENT_PASSWORD'] %>

test:
  secret_key_base: 0c936d2b014aacd86031336ccbd55349ab2e089052fc6a5fc2c807977c843480b0c712ab3b9462ee506d4444c6f6c6a0f31bb07c6282be910a04d2accc0dfd4a
  db_host: <%= ENV['DESTINY_TEST_HOSTNAME'] %>
  db_name: <%= ENV['DESTINY_TEST_DATABASE'] %>
  db_user: <%= ENV['DESTINY_TEST_USERNAME'] %>
  db_pass: <%= ENV['DESTINY_TEST_PASSWORD'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
